services:
  - type: web
    name: lucky-motos-backend
    env: java
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/sistemamotoservice-0.0.1-SNAPSHOT.war
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 10000
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
    plan: free

